services:

  interactive:
    build:
      context: .
      dockerfile: Dockerfile.interactive
      args:
        TCLPLUGIN_RPM_URL: ${TCLPLUGIN_RPM_URL:-https://github.com/jimregan/tclplugin/releases/download/fc3-rpm-3.1-1/tclplugin-3.1-1.i386.rpm}
        SNACK_RPM_URL: ${SNACK_RPM_URL:-https://github.com/jimregan/tclplugin/releases/download/fc3-rpm-3.1-1/snack-2.2.10-1.i386.rpm}
    image: fc3-interactive
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "2222:2222"
      - "8000:8000"
    volumes:
      - .:/workspace
      - ./rpmbuild:/rpmbuild


  final:
    build:
      context: .
      dockerfile: Dockerfile.final
      args:
        TCLPLUGIN_RPM_URL: ${TCLPLUGIN_RPM_URL:-https://github.com/jimregan/tclplugin/releases/download/fc3-rpm-3.1-1/tclplugin-3.1-1.i386.rpm}
        SNACK_RPM_URL: ${SNACK_RPM_URL:-https://github.com/jimregan/tclplugin/releases/download/fc3-rpm-3.1-1/snack-2.2.10-1.i386.rpm}
    image: fc3-final
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "2222:2222"
      - "8000:8000"
    profiles:
      - final
