services:

  interactive:
    build:
      context: .
      dockerfile: Dockerfile.interactive
    image: fc3-interactive
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "2222:2222"
    volumes:
      - .:/workspace
      - ./rpmbuild:/rpmbuild

  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: fc3-builder
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - ./rpmbuild:/rpmbuild:ro
      - ./output:/output
    profiles:
      - build

  final:
    build:
      context: .
      dockerfile: Dockerfile.final
    image: fc3-final
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "2222:2222"
    profiles:
      - final
