services:

  interactive:
    build:
      context: .
      dockerfile: Dockerfile.interactive
    image: rhl72-interactive
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "2222:2222"

  final:
    build:
      context: .
      dockerfile: Dockerfile.final
    image: rhl72-final
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
    profiles:
      - final
