FROM rhl72-base

# Bake the disk image in at build time so this image is self-contained.
# Build with:
#   docker build -f Dockerfile.build \
#     --build-arg DISK_IMAGE=disk/rhl72.qcow2 \
#     -t rhl72-build .
ARG DISK_IMAGE=disk/rhl72.qcow2
COPY ${DISK_IMAGE} /disk/rhl72.qcow2

COPY rpmbuild/ /rpmbuild/

CMD ["/rhl72/scripts/run-build.sh"]
