FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    qemu-system-i386 \
    qemu-utils \
    qemu-system-common \
    python3 \
    genisoimage \
    dosfstools \
    isolinux \
    rsync \
    wget \
    openssh-client \
    sshpass \
    expect \
    novnc \
    websockify \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /disk

WORKDIR /rhl72

COPY scripts/ /rhl72/scripts/
RUN chmod +x /rhl72/scripts/*.sh
