FROM rhl72-installed

COPY scripts/ /rhl72/scripts/
RUN chmod +x /rhl72/scripts/*.sh

COPY output/ /rpms/
RUN bash /rhl72/scripts/install-rpm-in-vm.sh

EXPOSE 6080
EXPOSE 2222

CMD ["bash", "/rhl72/scripts/run-final.sh"]
